### ISSUE TITLE
All text highlighted on app returned focus can cause unexpected overwrite

### ISSUE THREAD

**Issue by Valamas** [Ezzpify/SteamBulkActivator#2]
When focus leaves and then returns to the activator app, the app auto-highlights all text of any keys already entered. This could cause the overwrite of keys not already activated. This is a usability problem as the process as I see it is to copy each key from say a web browser page and paste it in to a new line in the activator.

Instead of highlighting the whole text area, the text cursor should remain unchanged. At the very most, on paste, auto add a line return (probably a desired behaviour).

I worked around this by pasting keys in to a notepad app first then transferring the bulk to the activator so I did not have to realign the cursor position before each paste.

great app, thank you for it.

**Comment by Ezzpify** [comment]
Hello @Valamas and thanks for the report. I was not able to replicate this problem, but I did make a change so that it now uses a RichTextBox element rather than a TextBox. I originally went with TextBox, regardless of the cons, because it allowed for text center. However, now it should work better since you can Ctrl+A and make use of the scroll bar.

Let me know if this update fixed the issue you had!

https://github.com/Ezzpify/SteamBulkActivator/releases/tag/1.0.4

**Comment by Valamas** [comment]
The update fixed the problem. Great work and thank you!
